### ISSUE TITLE
function2/function2.hpp': No such file or directory

### ISSUE THREAD

**Issue by chenscottus** [Ahajha/LMRTFY#4]
lmrtfy\thread_pool.hpp	13	
Cannot open include file: 'function2/function2.hpp': No such file or directory	

Thanks

**Comment by Ahajha** [comment]
Are you building LMRTFY with CMake? If so, it should pull the dependency for you. If not, you can manually pull function2 (there is a link in the CMakeLists.txt) and pass `-I path/to/function2` to your compiler flags.

**Comment by chenscottus** [comment]
Thanks
